---
title: "Overstory Tree Data Exploration"
author: "Randy Swaty"
date: "2023-03-22"
output: html_document
---


## The basics



```{r set up, message=FALSE, warning=FALSE, include=FALSE}

# load packages

library(crosstalk)
library(ggsci)
library(plotly)
library(scales)
library(tidyverse)


# read in data, round numbers to whole numbers
overstory_data <- read_csv("data/overstory.csv") %>%
  mutate(ave_basal_area_whole = round(ave_basal_area, 0)) %>%
  group_by(sitename) %>%
  mutate(sitename = fct(rev(sitename)))
  
  
```

```{r grouped  by species, echo=FALSE, message=FALSE, warning=FALSE}

grouped_species <- overstory_data %>%
  group_by(species_trees)%>%
  summarise(mean_basal_area = mean(ave_basal_area_whole))

grouped_species_chart  <- 
  ggplot(data = grouped_species, aes(x = species_trees, y = mean_basal_area)) +
  geom_bar(stat = "identity", fill = "purple") +
  labs(
    title = "Mean Basal Area by Species across all sites",
    x = "",
    y = "Basal Area") +
  scale_x_discrete(limits = rev(grouped_species$species_trees)) +
  coord_flip() +
  theme_bw()

grouped_species_chart
```


## Overstory basal area per site

```{r clickable species by site, echo=FALSE, message=FALSE, warning=FALSE}

# set up key for crosstalk

sd_overstory_data <- highlight_key(overstory_data)



basal_area_chart <- 
  ggplot(sd_overstory_data, aes(x = species_trees,
                                 y = ave_basal_area_whole)) +
  geom_point(size = 3,
             colour = "#4c0185") +
  labs(
    title = "Average Basal Area per Species",
    x = "",
    y = "Basal Area") +
  scale_y_continuous(labels = comma) +
  theme_bw()

bscols(widths = c(3, 10),
       filter_select("BP", 
                     "Select site", 
                     sd_overstory_data, 
                     ~ sitename,
                     multiple = FALSE),
       ggplotly(basal_area_chart,
                tooltip = FALSE,
                width = 815)
)


```



## Looking across all of the sites


```{r all sites, echo=FALSE, message=FALSE, warning=FALSE, fig.height=12}
plot <-
  ggplot(overstory_data, aes(fill = species_trees, y = ave_basal_area_whole, x = sitename)) +
  geom_bar(position = "stack", stat = "identity") +
  coord_flip() +
  labs(
    title = "Conversion status of our 402 ecosystems",
    subtitle = "Conversion status of our 402 ecosystems",
    caption = "Data from landfire.gov.",
    x = "",
    y = "Acres",
    fill = "Status")+
  scale_x_discrete(limits=rev) +
  scale_y_continuous(label=comma) + 
  theme_bw() + 
  scale_fill_manual(values = c(
                              "dodgerblue2", 
                              "#E31A1C", 
                              "#0b4222",
                              "#6A3D9A", # purple
                              "#FF7F00", # orange
                              "#ab520e", 
                              "black",
                              "skyblue2", 
                              "#FB9A99", # lt pink
                              "palegreen2",
                              "#CAB2D6", # lt purple
                              "#FDBF6F", # lt orange
                              "gray70", 
                              "khaki2",
                              "maroon", 
                              "orchid1", 
                              "deeppink1", 
                              "#ebf06e"))+
  theme(plot.caption = element_text(hjust = 0, face= "italic"), #Default is hjust=1
        plot.title.position = "plot", #NEW parameter. Apply for subtitle too.
        plot.caption.position =  "plot") 

plot

```

