---
title: "Understory Data Exploration"
author: "Randy Swaty"
date: "2023-03-22"
output:
  html_document:
    toc: true
    toc_float: true
---

## The basics

Most data cleaning was in an Excel pivot table.  Blanks were removed.  This should be considered draft subject to QA/QC.  Raw data that includes blanks is at bottom of page. 

<br>

```{r us set up, message=FALSE, warning=FALSE, include=FALSE}

# load packages

library(crosstalk)
library(ggsci)
library(kableExtra)
library(plotly)
library(scales)
library(tidyverse)

# read in data, round numbers to whole numbers
understory_data_raw <- read_csv("data/understory.csv") %>%
  group_by(sitename) %>%
  mutate(sitename = fct(rev(sitename)))
  
## remove blanks
understory_data <- read_csv("data/understory.csv", col_types = cols(tpa = col_number())) %>%
  group_by(sitename) %>%
  mutate(sitename = fct(rev(sitename))) %>%
  filter(!dbh_class %in% "(blank)")

```




```{r grouped  by species, echo=FALSE, message=FALSE, warning=FALSE}

grouped_species <- understory_data %>%
  group_by(species_seedlings)%>%
  summarize(mean_seedlings = mean(tpa))

grouped_species_chart  <- 
  ggplot(data = grouped_species, aes(x = species_seedlings, y = mean_seedlings)) +
  geom_bar(stat = "identity", fill = "#43334d", na.rm = TRUE) +
  labs(
    title = "Mean number of seedlings by species across all sites",
    x = "",
    y = "Mean trees per acre") +
  scale_x_discrete(limits = rev(grouped_species$species_seedlings)) +
  coord_flip() +
  theme_bw()

grouped_species_chart
```


## Basal area per species

<br>

```{r grouped bar us, echo=FALSE, message=FALSE, warning=FALSE, fig.height= 10, fig.width= 9}

grouped_species_ba <- understory_data %>%
  group_by(species_seedlings, dbh_class) %>%
  summarise(mean_seedlings = mean(tpa))
  

ba_species_chart  <- 
  ggplot(data = grouped_species_ba, aes(x = species_seedlings, 
                                     y = mean_seedlings,
                                     fill = dbh_class)) + 
  geom_col(colour="black",
           width=0.9, 
           position=position_dodge2(preserve = "single", width = 0.5)) +
  labs(
    title = "Mean trees per acre class by species",
    x = "",
    y = "Mean trees per acre",
    cols = "DBH Class") +
  scale_x_discrete(limits = rev(grouped_species$species_seedlings)) +
  coord_flip() +
  theme_bw(base_size = 14) + 
  scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"), 
                    name="DBH class",
                    breaks = c("zero_to_one", "one_to_three", "three_to_five"),
                    labels = c("Small (0-1)", "Medium (1-3)", "Larger (3-5)"))

ba_species_chart




```

<br>

## Understory species and DBH by site

<br>
```{r understory click, echo=FALSE, message=FALSE, warning=FALSE, fig.height= 9, fig.width= 9}

sd_understory_data <- highlight_key(understory_data)



basal_area_chart <- 
  ggplot(sd_understory_data, aes(x = species_seedlings,
                                 y = tpa,
                                 fill = dbh_class )) +
  geom_jitter(size = 5,
              width = 0.3) +
  labs(
    title = "",
    x = "",
    y = "Trees per acre") +
    scale_fill_manual(values=c("#999999", "#E69F00", "#56B4E9"), 
                    name="DBH class",
                    breaks = c("zero_to_one", "one_to_three", "three_to_five"),
                    labels = c("Small (0-1)", "Medium (1-3)", "Bigly (3-5)")) +
  scale_y_continuous(labels = comma) +
  theme_bw()

bscols(widths = c(3, 10),
       filter_select("BP", 
                     "Select site", 
                     sd_understory_data, 
                     ~ sitename,
                     multiple = FALSE),
       ggplotly(basal_area_chart,
                tooltip = FALSE,
                width = 815)
)
```

<br>

## Pivoted and cleaned data (does have blanks)

```{r data table, echo=FALSE, message=FALSE, warning=FALSE}

kable(understory_data_raw,
      format.args = list(big.mark = ",")) %>%
  kable_styling(
    font_size = 12,
    bootstrap_options = c("striped", "hover", "condensed")
  ) 
```

